// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace King.Mapper.Generated.Sql
{
    using System;
    using System.Data;
    using King.Mapper.Data;

    /// <summary>
    /// Class that Represents dbo.SelectMultipleStatement Stored Procedure
    /// </summary>
	public partial class dboSelectMultipleStatement : IStoredProcedure
	{
        /// <summary>
        /// Gets Stored Proc name with Schema
        /// </summary>
		public string FullyQualifiedName()
		{
			return "dbo.SelectMultipleStatement";
		}

	}

    /// <summary>
    /// Class that Represents dbo.SimulatedInsertStatement Stored Procedure
    /// </summary>
	public partial class dboSimulatedInsertStatement : IStoredProcedure
	{
        /// <summary>
        /// Gets Stored Proc name with Schema
        /// </summary>
		public string FullyQualifiedName()
		{
			return "dbo.SimulatedInsertStatement";
		}

		#region Parameters
        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestInt", DbType.Int32)]
		public int? TestInt
		{
			get;
			set;
		}

		#endregion
	}

    /// <summary>
    /// Class that Represents dbo.SimulatedSelectStatement Stored Procedure
    /// </summary>
	public partial class dboSimulatedSelectStatement : IStoredProcedure
	{
        /// <summary>
        /// Gets Stored Proc name with Schema
        /// </summary>
		public string FullyQualifiedName()
		{
			return "dbo.SimulatedSelectStatement";
		}

		#region Parameters
        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestInt", DbType.Int32)]
		public int? TestInt
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestBigInt", DbType.Int64)]
		public long? TestBigInt
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestBit", DbType.Boolean)]
		public bool? TestBit
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestDecimal", DbType.Decimal)]
		public decimal? TestDecimal
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestMoney", DbType.Currency)]
		public decimal? TestMoney
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestFloat", DbType.Object)]
		public object TestFloat
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestDate", DbType.Object)]
		public object TestDate
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestDateTime2", DbType.Object)]
		public object TestDateTime2
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestDateTime", DbType.DateTime)]
		public DateTime? TestDateTime
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestChar", DbType.Object)]
		public object TestChar
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestText", DbType.Object)]
		public object TestText
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestNChar", DbType.Object)]
		public object TestNChar
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestNText", DbType.String)]
		public string TestNText
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestBinary", DbType.Object)]
		public object TestBinary
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestImage", DbType.Object)]
		public object TestImage
		{
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the parameter value
        /// </summary>
		[DataMapper("@TestGuid", DbType.Guid)]
		public Guid? TestGuid
		{
			get;
			set;
		}

		#endregion
	}

}